### PR TITLE
Add Lewis Profile and Headshot 

### PR DESCRIPTION
**Pull request by Decicco-Lewis**
@XinsongDu 
- could you please review this pull request adding my profile to the website. Thank you.

### CODE REVIEW

**Review by XinsongDu — CHANGES_REQUESTED** [review]
Great job. This pull request should be able to add you to our website, but some minor changes need to be made:
1. Move `fullsizeoutput_5a5.jpeg` to folder `images/people`
2. rename `fullsizeoutput_5a5.jpeg` to `Lewis_DeCicco.jpeg`
3. Modify the 4th line of file `Lewis_DeCicco.md` to `avatar: Lewis_DeCicco.jpeg`

Please push your change to GitHub again once you have made the above changes.

**Comment by XinsongDu** [comment]
@Decicco-Lewis

**Comment by XinsongDu** [comment]
Please also make sure that the portrait is 1:1.618 (width:height)

**Comment by Decicco-Lewis** [comment]
I updated the 4th line of the file and uploaded a headshot to the correct location. Please let me know if there are any other issues. @XinsongDu

**Review by XinsongDu — APPROVED** [review]
Great job! I will let you know if any further issue appears.

**Pull request merged**
